Vagrant.configure(2) do |config| 
  config.vm.box = "ubuntu/trusty64"

  config.vm.hostname = 'tomcat' 

  config.vm.provider 'virtualbox' do |virtualbox|
    virtualbox.linked_clone = true 
    virtualbox.name = 'tomcat'
    virtualbox.gui = false
    virtualbox.memory =  1024
    virtualbox.cpus = 1
    virtualbox.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    virtualbox.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.network "forwarded_port", guest: 8088, host: 8088, protocol: "tcp"
  
  config.vm.provision "file", source: "~/Tomcat-final-artifact/machine-content/port-modifier.sh", destination: "./machine-content/port-modifier.sh"
  config.vm.provision 'shell' do |initscript|
        initscript.path="user-data-scripts/user-data.sh"
  end
end